apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: scalar-ledger
    version: v1
  name: scalar-ledger
  namespace: scalardlt
spec:
  minReadySeconds: 120
  replicas: 3
  selector:
    matchLabels:
      k8s-app: scalar-ledger
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: scalar-ledger
        version: v1
    spec:
      initContainers:
      - name: cassandra-load-keyspace
        image: cassandra:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /init.cql
          name: scalar-ledger-config
          subPath: init.cql
        command:
        - /bin/bash 
        - -c 
        - "sleep 20 && echo loading cassandra keyspace && cqlsh cassandra.cassandra.svc.cluster.local -u cassandra -p cassandra -f /init.cql"
      containers:
      - name: scalar-legder
        image: pauldozancukscalar/scalardl-k8s:2.0.3
        imagePullPolicy: Always
        args:
        - sh
        - -c
        - dockerize  -template ledger.properties.tmpl:ledger.properties -wait tcp://${SCALAR_CASSANDRA_HOST}:${SCALAR_CASSANDRA_PORT}
          -timeout 30s /startup.sh
        env:
        - name: SCALAR_CASSANDRA_HOST
          value: cassandra.cassandra.svc.cluster.local
        - name: SCALAR_CASSANDRA_PORT
          value: "9042"
        - name: SCALAR_CASSANDRA_USERNAME
          value: cassandra
        - name: SCALAR_CASSANDRA_PASSWORD
          value: cassandra
        - name: CASSANDRA_REPLICATION_FACTOR
          value: "1"
        ports:
        - containerPort: 50051
          name: scalar-dl
          protocol: TCP
        - containerPort: 50052
          name: scalar-dl-priv
          protocol: TCP
        - containerPort: 50053
          name: scalar-dl-admin
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50051
          failureThreshold: 3
          initialDelaySeconds: 240
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50051
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        volumeMounts:
        - mountPath: /startup.sh
          name: scalar-ledger-config
          subPath: startup.sh
      imagePullSecrets:
      - name: reg-docker-secrets
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          defaultMode: 493
          name: scalar-ledger
        name: scalar-ledger-config