---
- name: Install Python3 Pip
  script: python_install.sh

- name: Install j2cli
  command: python3 -m pip install j2cli j2cli[yaml]

- name: Install Vim
  package:
    name: vim
    state: present
  register: install_vim_result
  until: install_vim_result is succeeded
  retries: 3
  delay: 5

- name: Install lvm2
  package:
    name: lvm2
    state: present
  register: install_lvm2_result
  until: install_lvm2_result is succeeded
  retries: 3
  delay: 5

- name: Install Prometheus Node Exporter
  block:
    - get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz
        dest: /tmp
    - file:
        path: "/etc/prometheus/node_exporter"
        state: directory
        mode: 0755
    - unarchive:
        src: /tmp/{{ NODE_EXPORTER_FILE | default('node_exporter-0.16.0.linux-amd64.tar.gz') }}
        dest: "/etc/prometheus/node_exporter"
        remote_src: yes
        extra_opts:
        - --strip-components=1
    - file:
        state: absent
        path: /tmp/{{ NODE_EXPORTER_FILE | default('node_exporter-0.16.0.linux-amd64.tar.gz') }}
    - copy:
        src: node_exporter.service
        dest: /etc/systemd/system/node_exporter.service
    - systemd:
        name: node_exporter
        enabled: yes
        daemon_reload: yes
        state: started
