# consider helm install to be failed after 10 minutes
helm-extra-args: --timeout 300s
check-version-increment: true
debug: true
chart-dirs:
  - charts/stable
validate-maintainers: false
namespace: default
release-label: test
