apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: scalar-envoy
    app.kubernetes.io/version: v1.0.0
  name: envoy
spec:
  minReadySeconds: 120
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: scalar-envoy
      app.kubernetes.io/version: v1.0.0
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scalar-envoy
        app.kubernetes.io/version: v1.0.0
    spec:
      imagePullSecrets:
      - name: reg-docker-secrets
      containers:
      - image: scalarlabs/scalar-envoy:1.0.0
        imagePullPolicy: Always
        name: envoy
        env:
        - name: admin_access_log_path
          value: "/dev/stdout"
        - name: internal_domain
          value: default.svc.cluster.local
        - name: scalardl_endpoint_address
          value: scalar-ledger-headless
        - name: envoy_tls
          value: "false"
        ports:
        - containerPort: 50051
        - containerPort: 50052
        - containerPort: 9001
        livenessProbe:
          httpGet:
            path: /ready
            port: 9001
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /ready
            port: 9001
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - scalardlpool
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - envoy
                topologyKey: kubernetes.io/hostname
              weight: 50
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/app
          operator: Equal
          value: scalardlpool
