apiVersion: v1
kind: Service
metadata:
  name: fluent-bit-logging-metrics
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  ports:
  - name: metrics
    port: 2020
    protocol: TCP
    targetPort: 2020
  selector:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
  type: ClusterIP
