---
- name: read tf modules
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
    DEBUG: yes
  tasks:

  - name: load network tfstate file
    shell: cat ../../examples/azure/network/terraform.tfstate
    register: network_json

  - name: retrieve bastion_ip and user_name from network tfstate
    set_fact:
      bastion_ip: "{{ (network_json.stdout | from_json).outputs.bastion_ip.value }}"
      user_name: "{{ (network_json.stdout | from_json).outputs.user_name.value }}"

  - debug:
      var: bastion_ip
    when: DEBUG

  - debug:
      var: user_name
    when: DEBUG

  - name: add bastion ip to host group
    add_host:
      hostname: bastion
      ansible_ssh_host: "{{ bastion_ip }}"
      ansible_user: "{{ user_name }}"
      groups: bastion

- name: deploy scalar ledger and envoy in kubernetes
  hosts: bastion
  gather_facts: no
  become: no
  roles:
  - "scalar.apps"
