---
- name: read tf modules
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
    DEBUG: yes
  tasks:
  - name: load network tfstate file
    include_vars:
      file: ../../examples/azure/network/terraform.tfstate
      name: tf_network_json

  - name: retrieve bastion_ip and user_name from network tfstate
    set_fact:
      bastion_ip: "{{ tf_network_json.outputs.bastion_ip.value }}"
      user_name: "{{ tf_network_json.outputs.user_name.value }}"

  - debug:
      var: bastion_ip
    when: DEBUG

  - debug:
      var: user_name
    when: DEBUG

  - name: add bastion ip to host group
    add_host:
      hostname: bastion
      ansible_ssh_host: "{{ bastion_ip }}"
      ansible_user: "{{ user_name }}"
      groups: bastion

  - name: load kubernetes tfstate file
    include_vars:
      file: ../../examples/azure/kubernetes/terraform.tfstate
      name: tf_kubernetes_json

  - name: retrieve kube_config from network tfstate
    set_fact:
      kube_config: "{{ tf_kubernetes_json.outputs.kube_config.value }}"

  - debug:
      var: kube_config
    when: DEBUG

  - name: copy the kube_config into tmp
    copy:
      content: "{{ kube_config }}"
      dest: ../tmp/kube_config

- name: install necessary kubernetes binary on bastion
  hosts: bastion
  gather_facts: no
  become: yes
  vars:
    KUBE_CONFIG: ../tmp/kube_config
  pre_tasks:
  - name: Switch Ansible's Python interpreter to Python 2
    set_fact:
      ansible_python_interpreter: "/usr/bin/python"
  - name: ensure libselinux-python3 is installed
    package:
      name: libselinux-python3
      state: present
  - name: Switch Ansible's Python interpreter to Python 3
    set_fact:
      ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - "scalar.kubectl"
    - "scalar.helm"
  tags:
  - kubernetes tool

- name: cleanup
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:
  - name: cleanup tmp kube_config
    file:
      path: ../tmp/kube_config
      state: absent
