---
- name: deploy tf modules
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
   TF_variables_file: example-us.tfvars
  tasks:
  - name: start terraform network
    terraform:
      project_path: ../../examples/azure/network/
      variables_file: "{{ TF_variables_file }}"
      state: present
    register: tf_run_network
    tags:
    - network

  - debug: msg={{ tf_run_network.outputs.bastion_ip.value }}
    tags:
    - network

  - debug: msg={{ tf_run_network.outputs.user_name.value }}
    tags:
    - network

  - name: start terraform kubernetes
    terraform:
      project_path: ../../examples/azure/kubernetes/
      variables_file: "{{ TF_variables_file }}"
      state: present
    register: tf_run_kubernetes
    tags:
    - kubernetes

  - debug: msg={{ tf_run_kubernetes.outputs.kube_config.value }} 
    tags:
    - kubernetes

  - name: start terraform cassandra
    terraform:
      project_path: ../../examples/azure/cassandra/
      variables_file: "{{ TF_variables_file }}"
      state: present
    tags:
    - cassandra
