---
- name: Download and install helm binary on admin server
  unarchive:
    src: "{{ HELM_URL }}"
    dest: /tmp
    copy: no

- name: Copy helm binary to $PATH
  copy:
    src: /tmp/linux-amd64/helm
    dest: "{{ HELM_PATH }}"
    mode: "0755"
    remote_src: yes

- name: Set permissions for helm binary
  file:
    path: "{{ HELM_PATH }}"
    mode: "0755"
