---
- name: Download and install helm binary on admin server
  get_url:
    url: "{{ HELM_URL }}"
    dest: /tmp/helm.tar.gz
    checksum: "sha256:{{ HELM_URL_CHECKSUM_SHA256 }}"

- name: Unarchive the helm tar
  unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp
    copy: no

- name: Copy helm binary to $PATH
  copy:
    src: /tmp/linux-amd64/helm
    dest: "{{ HELM_PATH }}"
    mode: "0755"
    remote_src: yes

- name: Clean /tmp/helm.tar.gz
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /tmp/linux-amd64
  - /tmp/helm.tar.gz

- name: Set permissions for helm binary
  file:
    path: "{{ HELM_PATH }}"
    mode: "0755"
