---
- name: Check if helm repository is setup
  stat:
    path: "{{ remote_home_user }}/.config/helm/repositories.yaml"
  register: helm_repository_check

- name: Add stable charts repository from helm
  command: "{{ helm_path }} repo add stable {{ helm_charts_repo }}"
  become: no
  when: not helm_repository_check.stat.exists
