{{- if  .Values.ledger.schemaImport.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "scalar-dl.fullname" . }}-ledger-schema
  labels:
    {{- include "scalar-dl-ledger.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "scalar-dl-ledger.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.ledger.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: schema-import
        image: "{{ .Values.ledger.image.repository }}:{{ .Values.ledger.image.version }}"
        imagePullPolicy: "{{ .Values.ledger.image.pullPolicy }}"
        command:
        - /bin/bash 
        - -c 
        -  "echo applying Scalar DL schema && dockerize --template create_schema.cql.tmpl:create_schema.cql && cqlsh --cqlversion=3.4.4 ${SCALAR_DB_CONTACT_POINTS} -u ${SCALAR_DB_USERNAME} -p ${SCALAR_DB_PASSWORD} -f create_schema.cql"
        env:
        - name: SCALAR_DB_CONTACT_POINTS
          value: "{{ .Values.ledger.scalarLedgerConfiguration.cassandraHost }}"
        - name: SCALAR_DB_CONTACT_PORT
          value: "{{ .Values.ledger.scalarLedgerConfiguration.cassandraPort }}"
        - name: SCALAR_DB_USERNAME
          value: "{{ .Values.ledger.scalarLedgerConfiguration.cassandraUsername }}"
        - name: SCALAR_DB_PASSWORD
          value: "{{ .Values.ledger.scalarLedgerConfiguration.cassandraPassword }}"
        - name: CASSANDRA_REPLICATION_FACTOR
          value: "{{ .Values.ledger.scalarLedgerConfiguration.replicationFactor }}"
      restartPolicy: Never
  backoffLimit: 0
{{- end }}
