apiVersion: batch/v1
kind: Job
metadata:
  name: scalardl-schema
spec:
  template:
    spec:
      containers:
      - name: cassandra
        image: cassandra:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/bash 
        - -c 
        - "echo loading cassandra keyspace && cqlsh ${SCALAR_DB_CONTACT_POINTS} -u ${SCALAR_DB_USERNAME} -p ${SCALAR_DB_PASSWORD} -f /init.cql"
        volumeMounts:
        - mountPath: /init.cql
          name: scalar-ledger-config
          subPath: init.cql
          readOnly: true
        env:
        - name: SCALAR_DB_CONTACT_POINTS
          value: cassandra-lb.internal.scalar-labs.com
        - name: SCALAR_DB_CONTACT_PORT
          value: "9042"
        - name: SCALAR_DB_USERNAME
          value: cassandra
        - name: SCALAR_DB_PASSWORD
          value: cassandra
      restartPolicy: Never
      volumes:
      - configMap:
          defaultMode: 256
          name: scalar-ledger
        name: scalar-ledger-config
backoffLimit: 0
