# Default values for schema-loading.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

schemaLoading:
  enabled: true

  database: cassandra
  contactPoints: cassandra
  contactPort: 9042
  username: cassandra
  password: cassandra
  replicationFactor: 3

  image:
    # schemaLoading.image.repository -- Docker image
    repository: scalarlabs/scalardl-schema-loader-cassandra
    # schemaLoading.image.tag -- Docker tag
    version: 1.0.0
    # schemaLoading.image.pullPolicy -- Specify a imagePullPolicy
    pullPolicy: IfNotPresent

  # schemaLoading.imagePullSecrets -- Optionally specify an array of imagePullSecrets. Secrets must be manually created in the namespace.
  imagePullSecrets: [name: reg-docker-secrets]
