apiVersion: v1
kind: Service
metadata:
  name: {{ include "scalar-envoy.fullname" . }}
  labels:
    {{- include "scalar-envoy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  selector:
    {{- include "scalar-envoy.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scalar-envoy.fullname" . }}-metrics
  labels:
    {{- include "scalar-envoy.labels" . | nindent 4 }}
spec:
  ports:
  - name: admin
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    {{- include "scalar-envoy.selectorLabels" . | nindent 4 }}
  type: ClusterIP
