---
- name: Install Docker From Script
  script: docker_install.sh
  become: yes

- name: Check if td-agent is installed
  package_facts:
    manager: auto

- name: Configure Docker to use fluentd logging driver by default if td-agent is installed
  block:
    - file:
        path: /etc/docker
        state: directory
    - copy:
        src: daemon.json
        dest: /etc/docker/daemon.json
  become: yes
  when: "'td-agent' in ansible_facts.packages"

- name: adding existing user '{{ ansible_user_id }}' to group docker
  user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: yes
  become: yes

- name: Install Git
  package:
    name: git
    state: present
  become: yes
  register: install_git_result
  until: install_git_result is succeeded
  retries: 3
  delay: 5


- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes

- name: Install cAdvisor
  block:
    - get_url:
        url: https://github.com/google/cadvisor/releases/download/v0.33.0/cadvisor
        dest: /usr/local/bin/cadvisor
        mode: 0755
    - copy:
        src: cadvisor.service
        dest: /etc/systemd/system/cadvisor.service
    - systemd:
        name: cadvisor
        enabled: yes
        daemon_reload: yes
        state: started
  become: yes
