---
- name: install necessary kubernetes binary on bastion
  hosts: bastion
  gather_facts: no
  become: yes
  vars:
    KUBE_CONFIG: tmp/kube_config
  roles:
    - "scalar.kubectl"
    - "scalar.helm"
  tags:
  - kubernetes tool
