---
- name: install necessary kubernetes binary on bastion
  hosts: bastion
  gather_facts: no
  become: yes
  vars:
    KUBE_CONFIG: tmp/kube_config
  roles:
    - "scalar.kubectl"
    - "scalar.helm"
  tags:
  - kubernetes tool

- name: cleanup 
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:
  - name: cleanup tmp kube_config
    file:
      path: tmp/kube_config
      state: absent