apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-metrics
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy
      app.kubernetes.io/version: v1.14.1
  endpoints:
  - port: admin
    path: /stats/prometheus
