{{- if  .Values.cassandra.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "schema-loading.fullname" . }}-cassandra
  labels:
    {{- include "schema-loading.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "schema-loading.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.cassandra.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: schema-import
        image: "{{ .Values.cassandra.image.repository }}:{{ .Values.cassandra.image.version }}"
        imagePullPolicy: "{{ .Values.cassandra.image.pullPolicy }}"
        env:
        - name: CASSANDRA_HOST
          value: "{{ .Values.cassandra.contactPoints }}"
        - name: CASSANDRA_PORT
          value: "{{ .Values.cassandra.contactPort }}"
        - name: CASSANDRA_USERNAME
          value: "{{ .Values.cassandra.username }}"
        - name: CASSANDRA_PASSWORD
          value: "{{ .Values.cassandra.password }}"
        - name: CASSANDRA_REPLICATION_FACTOR
          value: "{{ .Values.cassandra.replicationFactor }}"
      restartPolicy: Never
  backoffLimit: 0
{{- end }}
