apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scalar-ledger.fullname" . }}
  labels:
    {{- include "scalar-ledger.labels" . | nindent 4 }}
spec:
  minReadySeconds: 120
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "scalar-ledger.selectorLabels" . | nindent 6 }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "scalar-ledger.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 50051
          - containerPort: 50052
          - containerPort: 50053
          env:
          - name: SCALAR_DB_CONTACT_POINTS
            value: "{{ .Values.scalarLedgerConfiguration.cassandraHost }}"
          - name: SCALAR_DB_CONTACT_PORT
            value: "{{ .Values.scalarLedgerConfiguration.cassandraPort }}"
          - name: SCALAR_DB_USERNAME
            value: "{{ .Values.scalarLedgerConfiguration.cassandraUsername }}"
          - name: SCALAR_DB_PASSWORD
            value: "{{ .Values.scalarLedgerConfiguration.cassandraPassword }}"
          - name: SCALAR_DL_LEDGER_LOG_LEVEL
            value: "{{ .Values.scalarLedgerConfiguration.ledgerLogLevel }}"
          livenessProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=:50051
          readinessProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=:50051
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
