
---
- name: Check if docker-registry secrets exists in Kubernetes
  k8s_info:
    api_version: v1
    kind: Secret
    name: "{{kubernetes_registry_secret_name}}"
    namespace: "{{default_kubernetes_namespace}}"
  register: docker_registry_secrets 

- name: Add docker-registry secrets in Kubernetes
  shell: |
    #!/bin/bash
    kubectl create secret docker-registry {{ kubernetes_registry_secret_name }} --docker-server={{docker_registry}} --docker-username={{docker_username}} --docker-password={{docker_password}}
  when: not docker_registry_secrets.resources | length > 0

- name: Template configmap for envoy
  template:
    src: template/k8s_envoy.yaml.j2
    dest: "{{ remote_manifests_folder }}/configuration/envoy.yaml"

- name: Add configmap for envoy
  k8s:
    state: present
    src: "{{ remote_manifests_folder }}/configuration/envoy.yaml"
    namespace: "{{ default_kubernetes_namespace }}"

- name: Template configmap for schema for cassandra and ledger
  template:
    src: template/k8s_create_schema.cql.j2
    dest: "{{ remote_manifests_folder }}/configuration/create_schema.cql"

- name: Add config for schema for cassandra and ledger
  k8s:
    state: present
    src: "{{ remote_manifests_folder }}/configuration/create_schema.cql"
    namespace: "{{ default_kubernetes_namespace }}"
