
---
- name: Check if docker-registry secrets exists in Kubernetes
  k8s_info:
    api_version: v1
    kind: Secret
    name: "{{kubernetes_registry_secret_name}}"
    namespace: "{{default_kubernetes_namespace}}"
  register: docker_registry_secrets 

- name: Add docker-registry secrets in Kubernetes
  shell: |
    #!/bin/bash
    kubectl create secret docker-registry {{ kubernetes_registry_secret_name }} --docker-server={{docker_registry}} --docker-username={{docker_username}} --docker-password={{docker_password}}
  when: not docker_registry_secrets.resources | length > 0