---
- name: Create Namespace
  k8s:
    name: "{{ default_kubernetes_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy Fluentbit
  k8s:
    state: present
    src: "{{ item }}"
    namespace: "{{ default_kubernetes_namespace }}"
  with_items:
  - "{{ remote_manifests_folder }}/fluentbit/fluent-bit-configmap.yaml"
  - "{{ remote_manifests_folder }}/fluentbit/fluent-bit-role-binding.yaml"
  - "{{ remote_manifests_folder }}/fluentbit/fluent-bit-role.yaml"
  - "{{ remote_manifests_folder }}/fluentbit/fluent-bit-service-account.yaml"
  - "{{ remote_manifests_folder }}/fluentbit/fluent-bit-service.yaml"
  - "{{ remote_manifests_folder }}/fluentbit/fluent-bit-ds.yaml"

- name: Deploy service monitor for Fluentbit
  k8s:
    state: present
    src: "{{ remote_manifests_folder }}/fluentbit/fluent-bit-ds.yaml"
