KUBECTL_VERSION: v1.16.10
KUBECTL_PATH: /usr/local/bin/kubectl
KUBECTL_CONFIG: tmp/kube_config
KUBECTL_URL: "https://storage.googleapis.com/kubernetes-release/release/{{ KUBECTL_VERSION }}/bin/linux/amd64/kubectl"
KUBECTL_URL_CHECKSUM_SHA256: 246d36e4ce67e74e95ff2ba578b9189f58e5def0e8830a24cd30fa3cf279742f
PYTHON_PACKAGE: ['kubernetes', 'openshift', 'kubernetes-validate']
