apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus-operator
    release: prometheus
  name: prometheus-prometheus-envoy-alerts-rules
  namespace: monitoring
spec:
  groups:
  - name: Envoy Alerts
    rules:
    - alert: Envoy Pods errors
      expr: kube_pod_status_phase{namespace="default", pod=~"^scalar-envoy-.*", phase!="Running"} > 0
      labels:
        severity: warning
      annotations:
        summary: "one or many Envoy pods are in errors"
        description: "The Envoy container on {{ $labels.pod }} have an error."
