alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['cluster', 'alertname']
      group_wait: 15s
      group_interval: 1m
      repeat_interval: 30m
      # receiver: 'null'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'
      - match:
        receiver: 'team-slack'
        continue: true
    receivers:
    - name: 'null'
    - name: 'team-slack'
      slack_configs:
      - send_resolved: true
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
            *Description:* {{ .Annotations.description }}
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
        title_link: 'https://github.com/scalar-labs/scalar-k8s/tree/master/docs/alerts/{{ .GroupLabels.alertname }}.md'
