name: Ansible Lint on operation folder

on:
  pull_request:
    branches:
      - master
    paths:
      - "operation/**"
  push:
    branches:
      - master
    paths:
      - "operation/**"
jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: operation/**/*.(yml|yaml)
          args: --exclude=operation/config --exclude=operation/manifests
