name: 'Helm charts validate for scalar charts'
on:
  pull_request:
    branches:
      - master
    paths:
      - 'charts/stable/**'
  push:
    branches:
      - master
    paths:
      - 'charts/stable/**'
jobs:
  ct:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: lint
          config: .github/ct.yaml
    
  kubeval-chart:
    runs-on: ubuntu-latest
    needs: lint-chart
    strategy:
      matrix:
        # the versions supported by kubeval are the ones for
        # which a folder exists at
        # https://github.com/instrumenta/kubernetes-json-schema
        k8s:
          - v1.15.7

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Fetch history for chart testing
        run: git fetch --prune --unshallow
      
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh 


      # - name: Validate Helm Releases in test dir
      #   uses: stefanprodan/hrval-action@v3.1.0
      #   with:
      #     helmRelease: helm-charts/stable/scalar-envoy
      #     kubernetesVersion: 1.15.7
      #     helmVersion: v2
      
