name: 'Helm charts validate for scalar envoy'
on:
  pull_request:
    branches:
      - master
    paths:
      - 'helm-charts/stable/scalar-envoy/**'
  push:
    branches:
      - master
    paths:
      - 'helm-charts/stable/scalar-envoy/**'
jobs:
  hrval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Validate Helm Releases in test dir
        uses: stefanprodan/hrval-action@v3.1.0
        with:
          helmRelease: helm-charts/stable/scalar-envoy
          kubernetesVersion: 1.15.7
          helmVersion: v2
      
