name: 'Helm charts validate for scalar ledger'
on:
  pull_request:
    branches:
      - master
    paths:
      - 'charts/stable/scalar-ledger/**'
  push:
    branches:
      - master
    paths:
      - 'charts/stable/scalar-ledger/**'
jobs:
  ct:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
            
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: lint
          config: .github/ct.yaml
    
      # - name: Validate Helm Releases in test dir
      #   uses: stefanprodan/hrval-action@v3.1.0
      #   with:
      #     helmRelease: helm-charts/stable/scalar-ledger
      #     kubernetesVersion: 1.15.7
      #     helmVersion: v2
      