name: Helm testing and validate for scalar charts
on:
  pull_request:
    branches:
      - master
    # paths:
    #   - 'charts/stable/**'
  push:
    branches:
      - master
    # paths:
    #   - 'charts/stable/**'
jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: lint
          config: .github/ct.yaml

  kubeval-chart:
    runs-on: ubuntu-latest
    needs: lint-chart
    strategy:
      matrix:
        k8s:
          - v1.15.7
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Fetch history for chart testing
        run: git fetch --prune --unshallow
      
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh

  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - kubeval-chart
    strategy:
      matrix:
        k8s:
          - v1.15.11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history for chart testing
        run: git fetch --prune --unshallow

      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.0.0-rc.1
        with:
          config: .github/kind-cluster.yaml
          node_image: kindest/node:${{ matrix.k8s }}

      - name: Setup kubernetes (Kind) with registry, cassandra and schema
        run: |
          kubectl cluster-info
          kubectl create secret docker-registry reg-docker-secrets --docker-server=https://index.docker.io/v2/ --docker-username=${{ secrets.DOCKERHUB_USER }} --docker-password=${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          kubectl create -f .github/cassandra.yaml
          echo "Wait until cassandra is running" && sleep 100
          kubectl create -f .github/scalardl-schema.yaml
          echo "Wait until scalardl schema is completed" && sleep 60
          kubectl get po,svc,node -o wide

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: "install --all"
          config: .github/ct.yaml
