name: Detect deprecated Kubernetes APIs
on:
  pull_request:
    branches:
      - master
    paths:
      - playbooks/**
  push:
    branches:
      - master
    paths:
      - playbooks/**

jobs:
  pluto:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install pluto
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        wget https://github.com/FairwindsOps/pluto/releases/download/v3.0.1/pluto_3.0.1_linux_amd64.tar.gz
        tar xf pluto_3.0.1_linux_amd64.tar.gz
        rm -rf pluto_3.0.1_linux_amd64.tar.gz
        mv pluto $GITHUB_WORKSPACE/bin/pluto
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
        chmod +x $GITHUB_WORKSPACE/bin/pluto
    
    - name: Run pluto on playbooks folder
      run: pluto detect-files -d playbooks/
